<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<CodeBlocks_layout_file>
	<FileVersion major="1" minor="0" />
	<ActiveTarget name="Debug" />
	<File name="..\DivideByZeroException.h" open="1" top="0" tabpos="1" split="0" active="1" splitpos="0" zoom_1="0" zoom_2="0">
		<Cursor>
			<Cursor1 position="245" topLine="0" />
		</Cursor>
	</File>
	<File name="..\MathException.h" open="1" top="0" tabpos="4" split="0" active="1" splitpos="0" zoom_1="0" zoom_2="0">
		<Cursor>
			<Cursor1 position="139" topLine="0" />
		</Cursor>
	</File>
	<File name="..\MainException.cpp" open="1" top="1" tabpos="5" split="0" active="1" splitpos="0" zoom_1="0" zoom_2="0">
		<Cursor>
			<Cursor1 position="1366" topLine="52" />
		</Cursor>
	</File>
	<File name="..\OverflowException.h" open="1" top="0" tabpos="2" split="0" active="1" splitpos="0" zoom_1="0" zoom_2="0">
		<Cursor>
			<Cursor1 position="246" topLine="0" />
		</Cursor>
	</File>
	<File name="..\RootOfNegativeException.h" open="1" top="0" tabpos="3" split="0" active="1" splitpos="0" zoom_1="0" zoom_2="0">
		<Cursor>
			<Cursor1 position="270" topLine="0" />
		</Cursor>
	</File>
</CodeBlocks_layout_file>
